version: '3'
services:
  # nginx:
  #   image: nginx:latest
  #   ports:
  #     - 80:80
  #   restart: always  
  #   volumes:
  #     - ./nginx/conf.d:/etc/nginx/conf.d
  #     - /tmp/logs:/var/log/nginx

  redis-server:
    image: redis:latest
    ports:
      - 6380:6379
    restart: always

  db:
    image: mysql:8.0.2
    restart: always
    security_opt:
      - seccomp:unconfined
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=my_data
      - MYSQL_USER=my_user
      - MYSQL_PASSWORD=my_pw
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    ports:
      - "3306:3306"

  app:
    build: ./
    volumes:
      - ./:/usr/src/node-server/
      - /usr/src/node-server/node_modules
    restart: always
    working_dir: /usr/src/node-server/
    ports:
      - 3000:3000
    environment:
      - NODE_ENV: development
      - PORT: 3000
      - DB_USERNAME: my_user
      - DB_PASSWORD: my_pw
      - DB_DATABASE: my_data
      - DB_HOSTNAME: db
    command: npm start
    depends_on:
      - redis-server
      - db
    links:
      - redis-server:redis-server
      - db:db