version: '3'
services:
  # nginx:
  #   image: nginx:latest
  #   ports:
  #     - 80:80
  #   restart: always  
  #   volumes:
  #     - ./nginx/conf.d:/etc/nginx/conf.d
  #     - /tmp/logs:/var/log/nginx

  redis-server:
    image: redis:latest
    ports:
      - 6380:6379
    restart: always

  db:
    image: mysql:8.0.2
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD
      - MYSQL_DATABASE
    ports:
      - "3306:3306"

  app:
    build: ./
    volumes:
      - ./:/usr/src/node-server/
    restart: always
    working_dir: /usr/src/node-server/
    ports:
      - 3000:3000
    command: npm run prd
    depends_on:
      - redis-server
      - db
    links:
      - redis-server:rd
      - db:rd